### ISSUE TITLE
教程落后

### ISSUE THREAD

**Issue by hjkl950217** [Quorafind/MLNET-CN#1]
微软官网的教程变了，不再是预测情绪了。

我参考中文文档的教程时，发现`[Column(ordinal: "0")]`这种不行了，似乎是`API`换掉了.

建议发布正式版之后再更新文档，之前预览版的`API`可能被换。。

**Comment by Quorafind** [comment]
@hjkl950217 这个已经是接近一年以前的教程，我会在正式版更新以后直接更新文档，现在不建议使用这个教程。

**Comment by hjkl950217** [comment]
@Quorafind 恩恩  也感谢制作这些。。我是查资料时发现同一个问题（鸢尾花分类），有好多种版本。用了不同的模型
